// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfuOAxRxBctpzN_LP4Scfxa_3csFD-aM',
    appId: '1:471955134815:web:093aa30b2ef6861e783eea',
    messagingSenderId: '471955134815',
    projectId: 'mynotes-manpro-27604',
    authDomain: 'mynotes-manpro-27604.firebaseapp.com',
    storageBucket: 'mynotes-manpro-27604.appspot.com',
    measurementId: 'G-71NK5QCQXV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZfuOAxRxBctpzN_LP4Scfxa_3csFD-aM',
    appId: '1:471955134815:web:d4cdae11360aec32783eea',
    messagingSenderId: '471955134815',
    projectId: 'mynotes-manpro-27604',
    authDomain: 'mynotes-manpro-27604.firebaseapp.com',
    storageBucket: 'mynotes-manpro-27604.appspot.com',
    measurementId: 'G-7EM8NJK37H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zaCaEmtO8li5efFgb_WWIDuos3dI2eo',
    appId: '1:471955134815:android:d4355d54c9ace4d1783eea',
    messagingSenderId: '471955134815',
    projectId: 'mynotes-manpro-27604',
    storageBucket: 'mynotes-manpro-27604.appspot.com',
  );

}